project:
  type: website
  output-dir: docs
website:
  title: "Jing Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pubs.qmd
      - award.qmd
      - cv.qmd

format:
  html:
    theme: lumen
    css: styles.css
    page-layout: full
    toc: true

editor: visual

